# Generated by Django 3.0.2 on 2020-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('tdate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
